layout_spectrum: 0.7991984630934894
typography_spectrum: 0.5760566091630608
color:
  saturation: 0.2632612753659487
  brandStrength: 0.39784299582242966
  lightness: 0.25708468398079276
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.6465029788669199
title: ''
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
analytics:
  google: UA-79787653-1
