title: James Kumo
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5179211
  brandStrength: 0.8243728
  lightness: 0.6541219
  brandColors:
    - '#230924'
    - '#F7F4D5'
    - '#46303D'
    - '#B4A797'
    - '#826055'
  rhythmicContrast: 0.4910394
typography_spectrum: 0
description: DJ / Producer / Label Owner
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
layout_spectrum: 0.625448
analytics:
  google: UA-79787653-1
