title: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6953405
  brandStrength: 0.6738351
  lightness: 0.530466
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  rhythmicContrast: 0.5089605
typography_spectrum: 0.5469662148971111
description: DJ / Producer / Label Owner
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
analytics:
  google: UA-79787653-1
layout_spectrum: 0.7795699
name: James Kumo
