title: ''
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7544803
  brandStrength: 0.7956989
  lightness: 0.2078853
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  rhythmicContrast: 1
typography_spectrum: 0.2150538
description: ''
layout_spectrum: 0.2903226
analytics:
  google: UA-79787653-1
name: James Kumo
