title: ''
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7240143
  brandStrength: 0.3297491
  lightness: 0.4247312
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  rhythmicContrast: 0.3853047
typography_spectrum: 0
description: ''
layout_spectrum: 0.4946237
analytics:
  google: UA-79787653-1
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
