layout_spectrum: 0.5653226128779352
typography_spectrum: 0.5192525379825383
color:
  saturation: 0.2899674465879798
  brandStrength: 0.07676653191447258
  lightness: 0.9761721033137292
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  rhythmicContrast: 0.2972743979189545
title: ''
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/james.kumo/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/JamesKumo'
    type: external
  - name: Resident Advisor
    url: 'https://www.residentadvisor.net/dj/jameskumo'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/james_kumo/?hl=en'
    type: external
analytics:
  google: UA-79787653-1
