title: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6433692
  brandStrength: 1
  lightness: 0.3620072
  brandColors:
    - '#230924'
    - '#F7F4D5'
    - '#46303D'
    - '#B4A797'
    - '#826055'
  rhythmicContrast: 0.8960574
typography_spectrum: 0.374552
description: DJ / Producer / Label Owner
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
analytics:
  google: UA-79787653-1
layout_spectrum: 0.7383512
name: James Kumo
