title: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2168459
  brandStrength: 0.5698925
  lightness: 0.437276
  brandColors:
    - '#230924'
    - '#F7F4D5'
    - '#46303D'
    - '#B4A797'
    - '#826055'
  rhythmicContrast: 0.8136201
typography_spectrum: 0.1294813791755587
description: DJ / Producer / Label Owner
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
analytics:
  google: UA-79787653-1
layout_spectrum: 0.8620217172428966
name: James Kumo
