title: ''
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1272401
  brandStrength: 0
  lightness: 0.1684588
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  rhythmicContrast: 1
typography_spectrum: 0.3935486176051199
description: ''
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/james.kumo/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/JamesKumo'
    type: external
  - name: Resident Advisor
    url: 'https://www.residentadvisor.net/dj/jameskumo'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/james_kumo/?hl=en'
    type: external
layout_spectrum: 0
analytics:
  google: UA-79787653-1
