title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6541219
  brandStrength: 0.7885305
  lightness: 0.8698294
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.4807995
typography_spectrum: 0.7011376966256648
description: ''
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/james.kumo/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/JamesKumo'
    type: external
  - name: Resident Advisor
    url: 'https://www.residentadvisor.net/dj/jameskumo'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/james_kumo/?hl=en'
    type: external
analytics:
  google: UA-79787653-1
layout_spectrum: 0.5322581
name: James Kumo
