title: James Kumo
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4408602
  brandStrength: 0.2634408
  lightness: 0.7096774
  brandColors:
    - '#230924'
    - '#F7F4D5'
    - '#46303D'
    - '#B4A797'
    - '#826055'
  rhythmicContrast: 0.672043
typography_spectrum: 0
description: DJ / Producer / Label Owner
layout_spectrum: 0.625448
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
analytics:
  google: UA-79787653-1
