title: ''
name: James Kumo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8333333
  brandStrength: 0.4820789
  lightness: 0.5232975
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.646503
typography_spectrum: 0
description: ''
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
  - name: Resident Advisor
    id: 851117ac-7c12-4ea3-a614-c661c015cc9c
    type: content
  - name: Twitter
    id: 6dbc2d14-5dee-4cd9-bd83-8da9d23aa820
    type: content
analytics:
  google: UA-79787653-1
layout_spectrum: 0.7991984630934894
