typography_spectrum: 0.5469662148971111
color:
  saturation: 0.688172
  brandStrength: 0.4605735
  lightness: 0.4390681
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  rhythmicContrast: 0.5089605
layout_spectrum: 0.5860215
analytics:
  google: UA-79787653-1
name: James Kumo
navigation:
  - name: DJ Bookings
    id: d688c60e-a21f-49a9-9a52-fd1cdd47247f
    type: content
  - name: Resident Advisor
    id: 851117ac-7c12-4ea3-a614-c661c015cc9c
    type: content
  - name: Twitter
    id: 6dbc2d14-5dee-4cd9-bd83-8da9d23aa820
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: // DJ & Producer //
description: 'Manchester, UK'
